// Aukora Spatial — GRATICUBE data: 247 story cards + the two character frameworks.
// GENERATED from the owner's build brief (docs/GRATICUBE_BUILD_BRIEF.md)
// by a parser that validates every count against the brief's own summary tables —
// do not hand-edit cards here; regenerate from the canonical CSV/brief instead.
// Content © 2020-2026 Graticube (https://www.graticube.game) — used in this node with the owner's hand.

export const GRATICUBE_DICE = {
  time:  ['never', 'past', 'future', 'always', 'some time', 'now'],
  space: ['love', 'wisdom', 'gratitude', 'trust', 'joy', 'courage', 'shame', 'regret', 'fear', 'desire', 'anger', 'guilt'],
};

export const GRATICUBE_CHARACTERS = {
 "connector": {
  "name": "The Connector",
  "sub": "One who invites some or all players to share.",
  "chakra": 1,
  "framework": "alive",
  "twin": "facilitator",
  "gradient": "linear-gradient(90deg,#c76301,#b61f24)"
 },
 "explorer": {
  "name": "The Explorer",
  "sub": "Explores the \"what if\" moment and lets it flow.",
  "chakra": 2,
  "framework": "alive",
  "twin": "curiositor",
  "gradient": "linear-gradient(90deg,#b49500,#c76301)"
 },
 "noticer": {
  "name": "The Noticer",
  "sub": "One who is aware of their playful mind.",
  "chakra": 3,
  "framework": "alive",
  "twin": "self_aware",
  "gradient": "linear-gradient(90deg,#114b18,#b49500)"
 },
 "brave_heart": {
  "name": "Brave Heart",
  "sub": "Enjoys connection...giving and receiving kindness.",
  "chakra": 4,
  "framework": "alive",
  "twin": "purveyor_of_love",
  "gradient": "linear-gradient(90deg,#006d94,#114b18)"
 },
 "dreamweaver": {
  "name": "Dreamweaver",
  "sub": "Imagines what is possible with creative color.",
  "chakra": 5,
  "framework": "alive",
  "twin": "storyteller",
  "gradient": "linear-gradient(90deg,#293370,#006d94)"
 },
 "grateful_spirit": {
  "name": "Grateful Spirit",
  "sub": "One who appreciates what is special in every moment.",
  "chakra": 6,
  "framework": "alive",
  "twin": "apprecianado",
  "gradient": "linear-gradient(90deg,#361967,#293370)"
 },
 "uplifter": {
  "name": "The Uplifter",
  "sub": "Inspires a lighter and brighter moment for all.",
  "chakra": 7,
  "framework": "alive",
  "twin": "inspirator",
  "gradient": "linear-gradient(90deg,#a1366e,#361967)"
 },
 "listener": {
  "name": "The Listener",
  "sub": "One who listens deeply with an open heart and mind.",
  "chakra": 8,
  "framework": "both",
  "twin": "listener",
  "gradient": "linear-gradient(90deg,#b61f24,#a1366e)"
 },
 "facilitator": {
  "name": "Facilitator",
  "sub": "One who invites some or all players to share.",
  "chakra": 1,
  "framework": "shared",
  "twin": "connector",
  "gradient": "linear-gradient(90deg,#c76301,#b61f24)"
 },
 "curiositor": {
  "name": "Curiositor",
  "sub": "Explores the \"what if\" moment and lets it flow.",
  "chakra": 2,
  "framework": "shared",
  "twin": "explorer",
  "gradient": "linear-gradient(90deg,#b49500,#c76301)"
 },
 "self_aware": {
  "name": "Self-Aware",
  "sub": "One who considers an empowering aha moment.",
  "chakra": 3,
  "framework": "shared",
  "twin": "noticer",
  "gradient": "linear-gradient(90deg,#114b18,#b49500)"
 },
 "purveyor_of_love": {
  "name": "Purveyor of Love",
  "sub": "Enjoys connection...giving and receiving more love.",
  "chakra": 4,
  "framework": "shared",
  "twin": "brave_heart",
  "gradient": "linear-gradient(90deg,#006d94,#114b18)"
 },
 "storyteller": {
  "name": "Storyteller",
  "sub": "One who adds extra color and context to their share.",
  "chakra": 5,
  "framework": "shared",
  "twin": "dreamweaver",
  "gradient": "linear-gradient(90deg,#293370,#006d94)"
 },
 "apprecianado": {
  "name": "Apprecianado",
  "sub": "Reflects on an insight of gratitude and appreciation.",
  "chakra": 6,
  "framework": "shared",
  "twin": "grateful_spirit",
  "gradient": "linear-gradient(90deg,#361967,#293370)"
 },
 "inspirator": {
  "name": "Inspirator",
  "sub": "One who liberates a moment of inspiration.",
  "chakra": 7,
  "framework": "shared",
  "twin": "uplifter",
  "gradient": "linear-gradient(90deg,#a1366e,#361967)"
 }
};

export const GRATICUBE_DECKS = {
 "alive": {
  "label": "Alive",
  "framework": "alive",
  "description": "Alive core story prompts.",
  "sortOrder": 1
 },
 "alive_bonus": {
  "label": "Alive Bonus",
  "framework": "alive",
  "description": "Alive bonus story prompts.",
  "sortOrder": 2
 },
 "og": {
  "label": "OG",
  "framework": "shared",
  "description": "Original Graticube story prompts.",
  "sortOrder": 3
 },
 "abundance": {
  "label": "Abundance",
  "framework": "shared",
  "description": "Abundance story prompts.",
  "sortOrder": 4
 }
};

export const GRATICUBE_CARDS = [
 {"id":"abundance-27","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Describe your relationship with conformity or nonconformity."},
 {"id":"abundance-28","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"Like \"blowing dust off a mirror,\" you've just cleared an old limiting experience. What do you see now?"},
 {"id":"abundance-55","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"This is the Karma Card. How is karma a cause or effect in your life?"},
 {"id":"abundance-56","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"\"I am enough.\" How might this be true for you?"},
 {"id":"abundance-57","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"Is there a line of poetry that you know and would like to share?"},
 {"id":"abundance-58","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"How might others say you are an original?"},
 {"id":"abundance-59","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D2","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Who do you think could appreciate your appreciation?"},
 {"id":"abundance-60","source_decks":["abundance"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"How do you celebrate the gifts you've been given?"},
 {"id":"abundance-10","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"In a moment, you were magnetically attracted. How did your relationship with them or it evolve?"},
 {"id":"abundance-11","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C2","audience":"Youth","context":"Group-safe","energy":"Activating","prompt":"Who here is most motivated to create change?"},
 {"id":"abundance-12","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"The generosity of spirit is infinite. How might you access your spiritual birthright of abundance?"},
 {"id":"abundance-5","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe a time when money came to you easily."},
 {"id":"abundance-6","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"From this moment, you will get more out of life. What do you need to put in?"},
 {"id":"abundance-7","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You're playing this game because of choices you've made your entire life. What events brought you to this moment?"},
 {"id":"abundance-8","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"Have you ever had an intuitive feeling about a relationship that you did or did not follow?"},
 {"id":"abundance-9","source_decks":["abundance"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Start the first sentence of a story inspired by the cubes. Have the next person add the next sentence until it comes back to you to finish the story."},
 {"id":"abundance-1","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is the most important thing you have not yet accomplished?"},
 {"id":"abundance-2","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D2","complexity":"C4","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"Consider how you feel affected by this present moment. Invite others to share. How might we positively affect this moment?"},
 {"id":"abundance-3","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe a moment of synchronicity and/or your connection to Shakti (life force energy)."},
 {"id":"abundance-4","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You are about to embark on a magnificent human quest. What one item of creative intelligence will each of you bring?"},
 {"id":"abundance-41","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"Creative intelligence is consciousness in action. Are we using it or is it using us?"},
 {"id":"abundance-42","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Activating","prompt":"Is it true that we can make our own luck? If so, what might we co-create?"},
 {"id":"abundance-43","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Have you ever experienced turning no into yes, where everybody wins?"},
 {"id":"abundance-44","source_decks":["abundance"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C2","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"I need _____ hours of sleep, but..."},
 {"id":"abundance-29","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Hum aum and see if you can get others to hum along."},
 {"id":"abundance-30","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Who needs to be inspired and uplifted by you?"},
 {"id":"abundance-31","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Ignorance is bliss or \"consciousness is blissful.\" Which is true for you?"},
 {"id":"abundance-32","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"When you follow your bliss, where are you going?"},
 {"id":"abundance-33","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What do you enjoy giving to others?"},
 {"id":"abundance-34","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Welcome to being in the zone. All obstacles are disappearing. What are you excited to accomplish?"},
 {"id":"abundance-35","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is one of your favorite sources of inspiration?"},
 {"id":"abundance-36","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You have unlimited access to the ATM of Bliss. What is your secret..."},
 {"id":"abundance-37","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Share a moment of inspiration."},
 {"id":"abundance-61","source_decks":["abundance"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"\"Some people are so poor, all they have is money.\" - Bob Marley. What does wealth mean to you?"},
 {"id":"abundance-38","source_decks":["abundance"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What is a fixed belief about you that we should know?"},
 {"id":"abundance-39","source_decks":["abundance"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"There's a sense of peace here. What or who is contributing to it?"},
 {"id":"abundance-40","source_decks":["abundance"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What role do diverse people, places and/or ideas play in your life?"},
 {"id":"abundance-62","source_decks":["abundance"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"How might you rely on creative intelligence in some aspect of your life?"},
 {"id":"abundance-63","source_decks":["abundance"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Have you ever been in your own way?"},
 {"id":"abundance-20","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is your eraser for negativity?"},
 {"id":"abundance-21","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"In a moment you were misunderstood. What happened?"},
 {"id":"abundance-22","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D2","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Reflective","prompt":"Like a breath of fresh air, it feels as though all time has stopped. What caused this?"},
 {"id":"abundance-46","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"This is a get out of stress free card. How would you like to redeem it?"},
 {"id":"abundance-47","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Reflective","prompt":"Where do you see your love reflected?"},
 {"id":"abundance-48","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If a stranger gave you $500 to spend in the next five minutes on something that gives you true joy, how would you spend it?"},
 {"id":"abundance-49","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Think of a tiny moment of bliss. Open your heart to tell the story."},
 {"id":"abundance-50","source_decks":["abundance"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"How do you cultivate your state of inner affluence?"},
 {"id":"abundance-13","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What was your last \"aha moment?\" What might be your next one?"},
 {"id":"abundance-14","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Consider what you find yourself doing and what's not working. What's one thing you might choose to stop doing?"},
 {"id":"abundance-15","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"This is a free \"aha moment\" card. When do you apply it and what for?"},
 {"id":"abundance-16","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You just won the spiritual lottery. What is the emotional debt you would like to pay off?"},
 {"id":"abundance-17","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D3","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"Describe a time when it was difficult to speak the truth."},
 {"id":"abundance-18","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Reflective","prompt":"Describe a flattering or unflattering reflection in a relationship."},
 {"id":"abundance-19","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Grounding","prompt":"What is something you know you don't know?"},
 {"id":"abundance-45","source_decks":["abundance"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"\"Nothing is more natural than abundance.\" How is it manifesting?"},
 {"id":"abundance-23","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe a time when you turned consciousness into wealth."},
 {"id":"abundance-24","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"It's no secret that life is dynamic - all of us are tossed around by change. What change do you invite or reject?"},
 {"id":"abundance-25","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe a time when you got what you needed instead of what you wanted, or vice-versa."},
 {"id":"abundance-26","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You were blocked from getting what you wanted. What happened?"},
 {"id":"abundance-51","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"How do you support your own life and the life of others?"},
 {"id":"abundance-52","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Consider a moment you wish had been different. Like a movie director, describe the new scene as you desire."},
 {"id":"abundance-53","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"How do cooperation and competition affect your life?"},
 {"id":"abundance-54","source_decks":["abundance"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you are the hero's sidekick. When might you choose to stop the hero?"},
 {"id":"alive-15","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You get to invent a new holiday that everyone can celebrate, what's it all about?"},
 {"id":"alive-26","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What have you made with your hands that you're really proud of?"},
 {"id":"alive-45","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What art do you find beautiful? How do you describe it?"},
 {"id":"alive-48","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"In a moment, someone was left out, teased, or hurt. What was your part in it?"},
 {"id":"alive-59","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What's a funny or cool thing about you that not many people know?"},
 {"id":"alive-6","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could do one nice thing for someone, what would it be?"},
 {"id":"alive-63","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is something important you have lost?"},
 {"id":"alive-8","source_decks":["alive"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"What does it mean to be a good friend?"},
 {"id":"alive-31","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"You're not friends anymore. What happened?"},
 {"id":"alive-34","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Activating","prompt":"If you created the best school in the world, what would it be like?"},
 {"id":"alive-36","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You have a button that shows what everybody is really thinking. When would you use it?"},
 {"id":"alive-37","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"What should every teacher learn to do? Invite some or all players to share."},
 {"id":"alive-38","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You have an easy button. When do you press it? Who might you share it with?"},
 {"id":"alive-40","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What's the weirdest food combo you secretly love?"},
 {"id":"alive-52","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Who is one of your closest friends? What do you like about them?"},
 {"id":"alive-62","source_decks":["alive"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Grounding","prompt":"How do you know you can trust someone?"},
 {"id":"alive-16","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What would slow you down from accomplishing your dream? What would speed it up?"},
 {"id":"alive-17","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could help make someone's dream come true, whose would it be?"},
 {"id":"alive-21","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What do you enjoy doing so much that you forget about time?"},
 {"id":"alive-41","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine a perfect day. What is it like? Who is with you and what are you doing?"},
 {"id":"alive-50","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could be like anyone, who would it be?"},
 {"id":"alive-56","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"There is a door to a magic room. Where would you place the door? What's inside?"},
 {"id":"alive-57","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Activating","prompt":"Everyone playing gets to create a new planet, starting with you. What's it like?"},
 {"id":"alive-9","source_decks":["alive"],"framework":"alive","character_key":"dreamweaver","depth":"D2","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Who believes in your dreams?"},
 {"id":"alive-19","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D3","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"In a moment, you were challenged to be brave. What happened?"},
 {"id":"alive-2","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What do you know how to make in the kitchen?"},
 {"id":"alive-27","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Where does your mind go when you're bored?"},
 {"id":"alive-28","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you had a magic backpack, what magical things would it do?"},
 {"id":"alive-46","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could make any kind of art, what would you make?"},
 {"id":"alive-49","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You just stepped into a time machine. It can take you anywhere. Where are you going?"},
 {"id":"alive-55","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Activating","prompt":"You get to create an imaginary superhero pet. What in the world is it? What's its name?"},
 {"id":"alive-61","source_decks":["alive"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Grounding","prompt":"A job I would really like to know more about is..."},
 {"id":"alive-11","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Who or what makes you laugh?"},
 {"id":"alive-13","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is one of the most important things to you in the world?"},
 {"id":"alive-14","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What is one thing that you have now, that you want to keep for the rest of your life?"},
 {"id":"alive-18","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"When have you felt yourself smiling inside with pride?"},
 {"id":"alive-29","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's the best thing about living where you do?"},
 {"id":"alive-53","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"It's so exciting you can hardly wait. What is it?"},
 {"id":"alive-58","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is something interesting about your family?"},
 {"id":"alive-60","source_decks":["alive"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's a smell that reminds you of a favorite memory?"},
 {"id":"alive-22","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"What's a sound that makes you feel really happy or calm?"},
 {"id":"alive-23","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is something that makes you laugh?"},
 {"id":"alive-25","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could sing a duet with any famous singer, who would it be? What song?"},
 {"id":"alive-3","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"How do you know if someone is or is not ok?"},
 {"id":"alive-35","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What would you like your voice to be able to do?"},
 {"id":"alive-42","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What kinds of problems do you want to solve when you're older?"},
 {"id":"alive-7","source_decks":["alive"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You've just been asked to invent a new sport. What are some of your ideas?"},
 {"id":"alive-20","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something that most people don't notice about you?"},
 {"id":"alive-24","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What does \"being a good kid\" mean to you?"},
 {"id":"alive-30","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is one thing you promised not to do and did anyway?"},
 {"id":"alive-33","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is something you don't understand?"},
 {"id":"alive-43","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"What's the most colorful thing you've ever seen? How did you feel when you saw it?"},
 {"id":"alive-47","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"I wish I didn't have to..."},
 {"id":"alive-54","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"Your favorite thing to drink now makes you super smart. What is it and what do you want to know?"},
 {"id":"alive-64","source_decks":["alive"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"How will next year be different?"},
 {"id":"alive-1","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Who's a real hero in your life?"},
 {"id":"alive-10","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What advice might you give to someone who is sad?"},
 {"id":"alive-12","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you thought you couldn't do and you made it happen anyway?"},
 {"id":"alive-32","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What advice would you like to give to someone younger than you?"},
 {"id":"alive-39","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You get to change just one thing about the world. What is it?"},
 {"id":"alive-4","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you had one superpower that could change the world for good, what would it be?"},
 {"id":"alive-5","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Who is the most supportive person in your life?"},
 {"id":"alive-51","source_decks":["alive"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could accomplish only one thing this year, what would it be?"},
 {"id":"alive_bonus-10","source_decks":["alive_bonus"],"framework":"alive","character_key":"brave_heart","depth":"D3","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What do you consider difficult in life that is now easy?"},
 {"id":"alive_bonus-25","source_decks":["alive_bonus"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you thought you couldn't do and you made it happen?"},
 {"id":"alive_bonus-5","source_decks":["alive_bonus"],"framework":"alive","character_key":"brave_heart","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Have you ever been the bully or been bullied?"},
 {"id":"alive_bonus-52","source_decks":["alive_bonus"],"framework":"alive","character_key":"brave_heart","depth":"D3","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"You challenged someone in authority. What happened?"},
 {"id":"alive_bonus-20","source_decks":["alive_bonus"],"framework":"alive","character_key":"connector","depth":"D2","complexity":"C4","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"Invite each person playing to think of a person, place or thing. Tell a story that includes all of them."},
 {"id":"alive_bonus-24","source_decks":["alive_bonus"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"My favorite game to play with my friends is __________ because __________."},
 {"id":"alive_bonus-33","source_decks":["alive_bonus"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"What does it mean to be a super friend?"},
 {"id":"alive_bonus-38","source_decks":["alive_bonus"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"Who is the coolest person or group of people?"},
 {"id":"alive_bonus-40","source_decks":["alive_bonus"],"framework":"alive","character_key":"connector","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's something you've learned about a friend recently that surprised you? How did it make your friendship even stronger?"},
 {"id":"alive_bonus-11","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What's something you've always wanted?"},
 {"id":"alive_bonus-14","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Describe the perfect career."},
 {"id":"alive_bonus-27","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Activating","prompt":"Way to go! You created the funnest job ever. What is it?"},
 {"id":"alive_bonus-29","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Tonight you will have the craziest dream ever. What is it?"},
 {"id":"alive_bonus-31","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"How do you keep a dream ALIVE?"},
 {"id":"alive_bonus-45","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you have a secret garden that only you can visit. What would it look like?"},
 {"id":"alive_bonus-49","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you are a famous artist. What would you include in your art show?"},
 {"id":"alive_bonus-7","source_decks":["alive_bonus"],"framework":"alive","character_key":"dreamweaver","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"In 5 years from now, you get nominated as the best player. What is the game?"},
 {"id":"alive_bonus-1","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What food do you wish was good for you?"},
 {"id":"alive_bonus-18","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"The circus just called. They want you to choose animals for their show. What comes to mind?"},
 {"id":"alive_bonus-2","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What's a dance move you know, or one you want to learn?"},
 {"id":"alive_bonus-21","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine that you could be friends with ANY animal on the planet. What would you do together?"},
 {"id":"alive_bonus-22","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What's a \"good\" food you actually like?"},
 {"id":"alive_bonus-23","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"If I could survive and only eat this one food, it would be ___________. Why?"},
 {"id":"alive_bonus-3","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"You planted something in the ground. What happened?"},
 {"id":"alive_bonus-34","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"You have your own 10 foot pet dragon. What did you name it and where do you take it?"},
 {"id":"alive_bonus-36","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's a musical instrument you've always or never wanted to play?"},
 {"id":"alive_bonus-37","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine that aliens are real. How do you think life on their planet is?"},
 {"id":"alive_bonus-41","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Activating","prompt":"If you could build anything with Legos, what would you build, and how would it come to life?"},
 {"id":"alive_bonus-46","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could take an adventure anywhere, where would you go, and what would you bring with you?"},
 {"id":"alive_bonus-47","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you could taste a food that you've never tried before. What would it be?"},
 {"id":"alive_bonus-48","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"If you could touch anything in the world right now, what would you choose and why?"},
 {"id":"alive_bonus-51","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"What is the perfect climate?"},
 {"id":"alive_bonus-56","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could grow any plant in your backyard, what would it be?"},
 {"id":"alive_bonus-58","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What do you like to draw? How do you do it?"},
 {"id":"alive_bonus-6","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you just got an award for creating the best game on the planet. What is it for?"},
 {"id":"alive_bonus-8","source_decks":["alive_bonus"],"framework":"alive","character_key":"explorer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you have to get there really fast. How do you get there?"},
 {"id":"alive_bonus-16","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"When have you been most excited to wake up in the morning?"},
 {"id":"alive_bonus-17","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Something is happening, it's so exciting you can't sleep. What is it?"},
 {"id":"alive_bonus-19","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"It's a silly dance. One that makes you smile. What is it?"},
 {"id":"alive_bonus-26","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's the funniest thing that has ever happened to you?"},
 {"id":"alive_bonus-32","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is your favorite movie of all time?"},
 {"id":"alive_bonus-39","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"What makes you feel excited to wake up in the morning?"},
 {"id":"alive_bonus-55","source_decks":["alive_bonus"],"framework":"alive","character_key":"grateful_spirit","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is your favorite tree or plant? What makes it special?"},
 {"id":"alive_bonus-4","source_decks":["alive_bonus"],"framework":"alive","character_key":"listener","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you think is not ok to ask someone?"},
 {"id":"alive_bonus-57","source_decks":["alive_bonus"],"framework":"alive","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you're walking through a forest. What's the first thing you notice?"},
 {"id":"alive_bonus-12","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"How does luck show up in your life?"},
 {"id":"alive_bonus-13","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"What does it mean to be rich?"},
 {"id":"alive_bonus-15","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you have watched or read more than once, and why?"},
 {"id":"alive_bonus-35","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"When you look at a rainbow, what stands out to you?"},
 {"id":"alive_bonus-42","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"If your feelings were a color, what would they be?"},
 {"id":"alive_bonus-50","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What is something cool you know how to do?"},
 {"id":"alive_bonus-53","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What do you think your parents are doing right or wrong?"},
 {"id":"alive_bonus-54","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What art do you find beautiful? How might you describe it?"},
 {"id":"alive_bonus-9","source_decks":["alive_bonus"],"framework":"alive","character_key":"noticer","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine you are a pet. What instructions should your owner give?"},
 {"id":"alive_bonus-28","source_decks":["alive_bonus"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What superpower energy would you like to have that you could teach to the world?"},
 {"id":"alive_bonus-30","source_decks":["alive_bonus"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"The next time a bell rings somebody's dream will come true. What should it be?"},
 {"id":"alive_bonus-43","source_decks":["alive_bonus"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could help someone in a big way today, who would it be, and what would you do for them?"},
 {"id":"alive_bonus-44","source_decks":["alive_bonus"],"framework":"alive","character_key":"uplifter","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could invent a new superpower, what would it be? How would you use it to help others?"},
 {"id":"og-41","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's a meaningful way that you give or receive gratitude?"},
 {"id":"og-42","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D3","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What have you considered difficult in your life that is now easy?"},
 {"id":"og-43","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What would you put in a 30 minute vacation every day?"},
 {"id":"og-44","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you have watched or read more than once? Why?"},
 {"id":"og-45","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe a time you've been in \"flow\" (where your heart and head were in sync)."},
 {"id":"og-46","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Grounding","prompt":"Do you know why you were born?"},
 {"id":"og-47","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Describe a person you celebrate."},
 {"id":"og-48","source_decks":["og"],"framework":"shared","character_key":"apprecianado","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could ask one question of your ancestors, what would it be?"},
 {"id":"og-10","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Share a curious \"first-time\" experience."},
 {"id":"og-11","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Aliens have landed on Earth. How would you direct them to learn about us?"},
 {"id":"og-12","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could add one key to your computer / tablet / phone, what would it be and what would you have it do?"},
 {"id":"og-13","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"One of the wisest people on Earth is on hold waiting to talk to you. What question would you ask?"},
 {"id":"og-14","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"There's one cookie, your favorite, left on the plate at the party, do you eat it?"},
 {"id":"og-15","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"The doctor's office called: you no longer need any sleep. How is life different?"},
 {"id":"og-16","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is a worthy investment of your time?"},
 {"id":"og-9","source_decks":["og"],"framework":"shared","character_key":"curiositor","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you only accomplished one thing with the time that remains in this year, what would it be?"},
 {"id":"og-1","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D2","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Share what you believe you are doing right. Ask others to share what they think you are doing right."},
 {"id":"og-2","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Reflective","prompt":"What is something others can rely on you for? Ask others for their reflection about you, then share your answer."},
 {"id":"og-3","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Ask advice from the group. Each person playing may offer one sentence of advice to you."},
 {"id":"og-4","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Share one thing you like about each person playing. (Be sure to include yourself.)"},
 {"id":"og-5","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What do you think everyone playing the game has in common? Invite everyone to share."},
 {"id":"og-6","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C2","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"Describe success. Invite others to each share one sentence."},
 {"id":"og-7","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Describe someone who makes you smile."},
 {"id":"og-8","source_decks":["og"],"framework":"shared","character_key":"facilitator","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Describe one of your aspirations. Ask others to share why they think you may be called to it."},
 {"id":"og-49","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could only improve one thing about yourself in your lifetime, what would it be?"},
 {"id":"og-50","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you were told you had only one year to live, what would you do with this final year?"},
 {"id":"og-51","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you knew you couldn't fail, what would you do (differently)?"},
 {"id":"og-52","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D4","complexity":"C2","audience":"Universal","context":"Facilitated-only","energy":"Playful","prompt":"You've just broken through...what fear do you not have anymore?"},
 {"id":"og-53","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could change only one thing about the world, what would it be?"},
 {"id":"og-54","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Who is a real hero in your life?"},
 {"id":"og-55","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Describe a time when you felt inspired."},
 {"id":"og-56","source_decks":["og"],"framework":"shared","character_key":"inspirator","depth":"D2","complexity":"C2","audience":"Universal","context":"Pair","energy":"Grounding","prompt":"What is an idea you think everyone should know?"},
 {"id":"og-57","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Name one song that you turn up when you hear it and why."},
 {"id":"og-58","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Has anyone ever shared one of your secrets?"},
 {"id":"og-59","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Someone is talking about you. What are they saying?"},
 {"id":"og-60","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Share a time when you sang to yourself or to someone else."},
 {"id":"og-61","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could hear \"I love you\" from someone, from whom would it be most meaningful?"},
 {"id":"og-62","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D2","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Think of a project that you enjoy. Whose voice do you hear while doing it?"},
 {"id":"og-63","source_decks":["og"],"framework":"shared","character_key":"listener","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you would like others to ask you?"},
 {"id":"og-25","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What has most surprised you so far in your life?"},
 {"id":"og-26","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you could change one thing about your health in the next month, what would it be?"},
 {"id":"og-27","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What's one of your pet peeves?"},
 {"id":"og-28","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What is something important that you've lost?"},
 {"id":"og-29","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C4","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Before they die, or you do, what is something that you want to say? What might be keeping you from saying it?"},
 {"id":"og-30","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Imagine that you are a pet. What care instructions should your owner give the pet sitter?"},
 {"id":"og-31","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Describe what deep friendship means."},
 {"id":"og-32","source_decks":["og"],"framework":"shared","character_key":"purveyor_of_love","depth":"D1","complexity":"C3","audience":"Universal","context":"Group-safe","energy":"Playful","prompt":"If I could perform one miracle for someone in my life, it would be..."},
 {"id":"og-17","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Share a time when you made a mistake."},
 {"id":"og-18","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's one thing you promised never to do that you did anyway?"},
 {"id":"og-19","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's something you have been afraid to do or start?"},
 {"id":"og-20","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Where might you be playing too small in your life?"},
 {"id":"og-21","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is something you've been holding onto that you want to let go?"},
 {"id":"og-22","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"It's your last day on earth. Do you make your bed?"},
 {"id":"og-23","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"When is the hardest you've ever worked?"},
 {"id":"og-24","source_decks":["og"],"framework":"shared","character_key":"self_aware","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"How do you define and protect your boundaries?"},
 {"id":"og-33","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What is a job that you always or never wanted to have?"},
 {"id":"og-34","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"Name a time when your plans unexpectedly changed for the better."},
 {"id":"og-35","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C1","audience":"Youth","context":"Pair","energy":"Playful","prompt":"What wakes you up at night?"},
 {"id":"og-36","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Universal","context":"Pair","energy":"Playful","prompt":"What's something that you will never forget about a friend/sibling/parent/stranger?"},
 {"id":"og-37","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C2","audience":"Youth","context":"Pair","energy":"Playful","prompt":"Have you ever been caught... What happened?"},
 {"id":"og-38","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Describe a \"perfect\" day. (sarcasm allowed)"},
 {"id":"og-39","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C1","audience":"Youth","context":"Group-safe","energy":"Playful","prompt":"Describe a famous or favorite failure."},
 {"id":"og-40","source_decks":["og"],"framework":"shared","character_key":"storyteller","depth":"D1","complexity":"C3","audience":"Universal","context":"Pair","energy":"Playful","prompt":"If you were told you were performing stand-up comedy tonight, what would it be about?"}
];
